### ISSUE TITLE
How to build it in Visual Studio 2019?

### ISSUE THREAD

**Issue by ToCSharp** [sandboxie-plus/libApiLog#1]
Hello, tried to build LogApiDll in Visual Studio 2019.

1. libMinHook builds ok with n142 toolset and last Windows SDK
2. In LogApiDll\dll.vcxproj replace VC14 with VC15
3. Open logapi.sln, change toolset and Windows SDK
4. SystemWow64SharedInformation and ProcessTlsInformation undeclared, comment code with them
5. LNK1104	cannot open file 'libcntpr.lib'
6.? "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\km\x86\libcntpr.lib"
 And Library Dirs C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\km\x86\
 
 And I have such errors
![logapi_vs_errors](https://user-images.githubusercontent.com/16608023/104732243-f9cd1f00-574d-11eb-95ad-1aeaf7355bb6.PNG)

**Comment by DavidXanatos** [comment]
C++ -> Codegeneration -> Secrity Checks -> Disable Security Check (/GS-)

et voila

**Comment by NyaMisty** [comment]
It seems that the problem isn't that simple.
There's GS check enabled in newer WDK (in wlh/win7/win10 ddk). If not using libraries from wnet/wxp folder, even if the /GS was turned off in project settings, there'll still be linking errors.
However, ntdllp.lib was not present in wnet folder, but it do presents in your project linker input. I tried to use the one from wlh/win7 folder, but it failed with @__security_check_cookie@4 symbol missing too. Could you please tell me where to find it the correct ntdllp.lib?
